mysql_root_password: super-secure-password
mysql_bind_address: '0.0.0.0'
mysql_databases:
  - name: example_db
mysql_users:
  - name: example_user
    host: "%"
    password: similarly-secure-password
    priv: "example_db.*:ALL"
